version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"   # HTTP and WebSocket port
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - FASTAPI_URL=http://backend:80
    restart: unless-stopped
